version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 10

    # Optional niceties for PRs
    labels: ["dependabot", "dependencies"]
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"

    # Group minor/patch together; keep majors separate
    groups:
      minor-and-patch:
        applies-to: version-updates     # defaults to version-updates; explicit for clarity
        update-types:
          - minor
          - patch
        patterns:
          - "*"                         # match all packages
      majors:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"
