version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 10
    # Group minor+patch together (fast lane), keep majors separate
groups:
  minor-and-patch:
    update-types:
      - minor
      - patch
    patterns:
      - "*"
  majors:
    update-types:
      - major
    patterns:
      - "*"
    labels: ["dependabot", "dependencies"]
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
