version: 2
updates:
  # NPM packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels: ["dependabot", "dependencies"]
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
    # Group updates to reduce PR noise
    groups:
      dev-tools-minor-patch:
        applies-to: version-updates
        dependency-type: "development"
        update-types: ["minor", "patch"]
        patterns:
          - "jest*"
          - "eslint"
          - "@eslint/*"
          - "prettier"
      runtime-minor-patch:
        applies-to: version-updates
        dependency-type: "production"
        update-types: ["minor", "patch"]
        patterns:
          - "*"
      majors:
        applies-to: version-updates
        update-types: ["major"]
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    labels: ["dependabot", "dependencies"]
    commit-message:
      prefix: "chore"

      #
