name: Dependabot Auto-Merge (Minor/Patch)
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
permissions:
  contents: write
  pull-requests: write
jobs:
  enable-automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # Label majors for manual attention
      - name: Label majors as needs-manual
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-major' }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-manual-review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Auto-merge only minor/patch
      - name: Enable auto-merge
        if: |
          steps.meta.outputs.update-type == 'version-update:semver-minor' ||
          steps.meta.outputs.update-type == 'version-update:semver-patch'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
